### PR TITLE
removed incoming transactions chart, latest transactions list

### PR DESCRIPTION
**Pull request by polaris327**

### CODE REVIEW

**Comment by dambaev** [comment]
@polaris327 : I had checked that and the only issues I see:
1. your branch name is about 'slider-fix', but the commits are about removing stuff. Not that it will be reflected anyhow after the merge, but still, please keep this more in-sync in the future to not to confuse anyone ;) ;
2. diff shows, that you had just commented out blocks of html. I don't think, that there is a point to not to actually remove those blocks. We can get a history through git, in case if we will need to look for some removed code. But the actual removing helps to keep code base cleaner. So please, remove the commented blocks instead and then we will be ready for merging.

**Review by dambaev — CHANGES_REQUESTED** [review]
@polaris327  : I had checked that and the only issues I see:

1. your branch name is about 'slider-fix', but the commits are about removing stuff. Not that it will be reflected anyhow after the merge, but still, please keep this more in-sync in the future to not to confuse anyone ;) ;
2. diff shows, that you had just commented out blocks of html. I don't think, that there is a point to not to actually remove those blocks. We can get a history through git, in case if we will need to look for some removed code. But the actual removing helps to keep code base cleaner. So please, remove the commented blocks instead and then we will be ready for merging.

**Comment by polaris327** [comment]
@dambaev 
1. Yeah I will keep that in mind for future PRs.
2. Yeah totally agreed. I've removed them.

**Review by dambaev — APPROVED** [review]
this change is ok now

**Comment by dambaev** [comment]
@polaris327 : I have one more issue: as we have removed the view-part of the code, we still need to remove the controller part from the code, that is being unused now. For example:
dashboard.component.ts has `transactions$` and `mempoolStats$` variables, which are not needed and should be removed as well.

**Comment by polaris327** [comment]
@dambaev Fixed the issue

**Pull request merged**
